name: Run the tests on pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  run-pytest:
    name: 'run pytest tests'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      JENKINS_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      JENKINS_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      JENKINS_HOST: localhost
      JENKINS_PORT: 8080
      HEADLESS_MODE: true
      PLAYWRIGHT_BROWSERS_PATH: $HOME/.cache/ms-playwright/

    steps:
      - name: git clone
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ github.base_ref }}-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-

      - name: Debug pip cache location
        run: pip cache dir

      - name: install dependencies and playwright browsers
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Playwright version
        id: playwright-version
        run: |
          # Используем importlib.metadata для надежного получения версии установленного пакета 'playwright'
          PLAYWRIGHT_VERSION=$(python -c 'from importlib.metadata import version; print(version("playwright"))')
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/ms-playwright/
          key: ${{ runner.os }}-playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
            ${{ runner.os }}-playwright-browsers-

      - name: Debug Playwright cache location
        run: |
          echo "Playwright cache directory: $(playwright --version)"
          ls -la $HOME/.cache/ms-playwright/ || echo "Playwright cache directory does not exist"

      - name: Ensure Playwright Cache Directory Exists
        run: mkdir -p $HOME/.cache/ms-playwright/

      - name: Install Playwright Browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: python -m playwright install --with-deps

      - name: Debug Playwright cache location (After install)
        run: |
          echo "Playwright cache directory: $(playwright --version)"
          ls -la $HOME/.cache/ms-playwright/ || echo "Playwright cache directory does not exist"

      - name: prepare jenkins data
        run: |
          cat ${{ github.workspace }}/jenkins_data/jenkins_backup0* > ${{ github.workspace }}/jenkins_backup.tar.gz
          md5sum ${{ github.workspace }}/jenkins_backup.tar.gz

      - name: extract jenkins data and set permission
        run: |
          tar -xzvf ./jenkins_backup.tar.gz
          chmod -R 777 ./jenkins_backup/var/jenkins_home
          chmod -R 777 ./.github/

      - name: Docker start
        run: docker run --rm --detach -p 8080:8080 -v ${{ github.workspace }}/jenkins_backup/var/jenkins_home:/var/jenkins_home jenkins/jenkins:2.516.3-lts-jdk21

      - name: Wait for the Jenkins
        run: ./.github/wait-for-jenkins.sh

      - name: pytest run all tests
        run: pytest -v